# Site settings
title: Anthony Cossins — Front-end Developer
email: anthonyecossins@gmail.com
description: >
  Anthony Cossins has a website on the internet and this is it.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://anthonycossins.com"
enforce_ssl: anthonycossins.com

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed

# Collection definitions and settings
collections:
  posts:
    permalink: /blog/:title

  work:
    title: Work
    permalink: /:collection/:path/
    output: true
