# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# Site settings
title: Anthony Cossins — Designer / Developer
email: anthonyecossins@gmail.com
description: >
  Anthony Cossins has a website on the internet and this is it.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://anthonycossins.com"
enforce_ssl: anthonycossins.com
twitter_username: anthonyec
github_username:  anthonyec

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed

# Collection definitions and settings
collections:
  work:
    title: Work
    permalink: /:collection/:path/
    output: true
